"""Embed the LCD's fonts in data/observer-fx.js.

The observer's comic cut-ins are a port of ui-fx.hpp, and they are only the
same panels if they are lettered from the same glyphs. The board gets them
from LovyanGFX; the browser cannot, so this copies the three faces the FX
layer uses out of LovyanGFX's own headers into the block between
`@@FONTS-BEGIN` and `@@FONTS-END` in data/observer-fx.js:

  FreeSansBoldOblique24pt7b   the SFX lettering (continuous-bit GFX glyphs)
  glcdfont.h (Font0)          the 5x7 terminal hand, chars 32-127
  Font16.h (Font2)            the caption boxes, chars 32-127

    python scripts/gen_observer_fx_fonts.py [path/to/LovyanGFX]

Re-run only if LovyanGFX's fonts change, which in practice is never. The
Font16.h `#else` trap noted in memory applies here too: the header carries two
#ifdef/#else variant blocks and both macros are defined, so the #else arms are
dead and must be dropped before the numbers are read.
"""
import base64, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, "data", "observer-fx.js")


def find_lgfx(argv):
    cands = argv[1:2] + [os.environ.get("LOVYANGFX_DIR", "")]
    cands += [os.path.expanduser("~/Documents/Arduino/libraries/LovyanGFX")]
    cands += glob.glob(os.path.expanduser("~/OneDrive*/Documents/Arduino/libraries/LovyanGFX"))
    for c in cands:
        if c and os.path.isdir(os.path.join(c, "src", "lgfx", "Fonts")):
            return os.path.join(c, "src", "lgfx", "Fonts")
    sys.exit("LovyanGFX not found; pass its directory as the first argument")


def strip_comments(src):
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    return re.sub(r"//[^\n]*", "", src)


def gfx(path, name):
    src = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    bm = src[src.index(name + "Bitmaps"):]
    bm = bm[bm.index("{") + 1:bm.index("};")]
    bits = bytes(int(t, 16) for t in re.findall(r"0x([0-9A-Fa-f]{2})", bm))
    gl = src[src.index(name + "Glyphs"):]
    gl = gl[gl.index("{") + 1:gl.index("};")]
    glyphs = [tuple(int(v) for v in m.groups())
              for m in re.finditer(r"\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}", gl)]
    tail = src[src.index("const GFXfont " + name):]
    first, last, yadv = [int(t, 0) for t in re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", tail)[-3:]]
    assert len(glyphs) == last - first + 1, (len(glyphs), first, last)
    return bits, glyphs, first, last, yadv


def glcd(path):
    src = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    body = src[src.index("{", src.index("font[]")):]
    body = body[:body.index("};")]
    b = bytes(int(t, 16) for t in re.findall(r"0x([0-9A-Fa-f]{1,2})", body))
    return b[32 * 5:128 * 5]


def font2(path):
    src = strip_comments(open(path, encoding="utf-8", errors="replace").read())
    src = re.sub(r"#else.*?#endif", "", src, flags=re.S)
    wt = src[src.index("widtbl_f16"):]
    wt = wt[wt.index("{") + 1:wt.index("};")]
    widths = [int(t, 0) for t in re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", wt)][:96]
    chars = {}
    for m in re.finditer(r"chr_f16_([0-9A-Fa-f]{2})\s*\[[^\]]*\]\s*=\s*\{(.*?)\}", src, re.S):
        chars[int(m.group(1), 16)] = bytes(int(t, 16) for t in re.findall(r"0x([0-9A-Fa-f]{1,2})", m.group(2)))
    blob, off = bytearray(), []
    for c in range(32, 128):
        off.append(len(blob))
        blob += chars.get(c, b"")
    return widths, bytes(blob), off


def main():
    F = find_lgfx(sys.argv)
    bits, glyphs, first, last, yadv = gfx(os.path.join(F, "GFXFF", "FreeSansBoldOblique24pt7b.h"),
                                          "FreeSansBoldOblique24pt7b")
    g0 = glcd(os.path.join(F, "glcdfont.h"))
    w2, b2, o2 = font2(os.path.join(F, "Font16.h"))
    flat = ",".join(str(v) for g in glyphs for v in g)
    b = lambda x: base64.b64encode(x).decode("ascii")
    block = (
        "  // Generated by scripts/gen_observer_fx_fonts.py from LovyanGFX's own headers --\n"
        "  // the glyphs the LCD letters its panels in. Do not edit by hand.\n"
        "  const FONT = {\n"
        "    sfx: { first: %d, last: %d, yAdv: %d,\n"
        "           g: [%s],\n"
        "           bits: '%s' },\n"
        "    glcd: '%s',\n"
        "    f2: { w: [%s],\n"
        "          off: [%s],\n"
        "          bits: '%s' },\n"
        "  };\n"
    ) % (first, last, yadv, flat, b(bits), b(g0), ",".join(map(str, w2)), ",".join(map(str, o2)), b(b2))
    js = open(TARGET, encoding="utf-8").read()
    a, z = js.index("// @@FONTS-BEGIN"), js.index("// @@FONTS-END")
    a = js.index("\n", a) + 1
    z = js.rindex("\n", 0, z) + 1
    js = js[:a] + block + js[z:]
    open(TARGET, "w", encoding="utf-8", newline="\n").write(js)
    print("fonts embedded: sfx %d glyphs / %d bytes, glcd %d bytes, font2 %d bytes"
          % (len(glyphs), len(bits), len(g0), len(b2)))


if __name__ == "__main__":
    main()
